config/routes.rb
Rails4tutorialSampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root 'static_pages#home'
  
  match '/help',     to: 'static_pages#help',     via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/signup',   to: 'users#new',             via: 'get'
  match '/signup',   to: 'users#create',          via: 'post'

  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'
  match '/',         to: 'microposts#create',     via: 'post'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  # We have to specify the foreign key explicitly, since AR convention by default would look
  # for a foreign key named user_id.
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_relationships, foreign_key: 'followed_id',
                                   class_name:  'Relationship',
                                   dependent:   :destroy
  # We want User objects to respond to a followed_users method that returns a collection of
  # followed users. We can do this by establishing a has_many association through
  # relationships.
  # 
  # A relationship object responds to the #followed method and returns an AR User object.
  # We can specify that a user has many followed users by going *through* the relationship
  # model. Convention dictates that the relationships table should have a foreign key that
  # matches the name of this method (i.e. followed_user_id)
  has_many :followed_users, through: :relationships, source: :followed
  # Don't have to specify source because "followers" matches the convention of the foreign
  # key convention by looking for follower_id.
  has_many :followers,      through: :reverse_relationships

  before_save   { email.downcase! }
  # Before the user gets created in the DB, generate a remember token for them so that
  # they are not blank. We want this only on create, not on save (which would encompass
  # updates to the user)
  before_create :create_remember_token

  validates :name, 	presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: 	true,
  									format: 		{ with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def feed
    # TODO: We'll change this to be better!
    microposts
  end

  def follow!(user)
    self.relationships.create!(followed_id: user.id)
  end

  def unfollow!(user)
    self.relationships.find_by(followed_id: user.id).destroy!
  end

  def following?(user)
    self.relationships.find_by(followed_id: user.id)
  end

  # Generates a new remember token
  def self.new_remember_token
    # Generates a random URL-safe base64 string
    SecureRandom.urlsafe_base64
  end

  # Returns an encrypted form of the remember token
  def self.encrypt(token)
    # SHA1 is fast but not secure. That's okay -- we need it to be fast because
    # every page that a signed-in user accesses will need to encrypt?????
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    # Generates, encrypts, and then saves a new remember token for a user
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    redirect_to root_url if signed_in?
    @user = User.new
  end

  def edit
    # @user is set by correct_user before_action filter
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Sample App!'
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    # @user is set by correct_user before_action filter
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if user == current_user
      flash[:error] = 'You cannot delete yourself!'
    else
      user.destroy
      flash[:notice] = 'User deleted'
    end
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  # Strong params -- anywhere you'd previously pass in params willy-nilly, replace with
  # calls to a private method such as below.
  #
  # #require is an ActionController::Parameters instance method that looks at the parameters
  # and requires that the given key exists. If it does, it returns the paramter at that key.
  #
  # #permit is also an ActionController::Parameters instance method. It takes in one or more
  # attribute names as symbols and returns the params filtered to only those attributes.
  #
  # In this example, require returns the user hash, and permit filters that user hash such
  # that it contains only the permitted attributes.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns Gravatar image tag for a user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_fields.html.haml
= render 'shared/error_messages', object: f.object

=f.label :name
=f.text_field :name

=f.label :email
=f.text_field :email

=f.label :password
=f.password_field :password

=f.label :password_confirmation, 'Confirm password'
=f.password_field :password_confirmation

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id)) do |f|
  = f.hidden_field :followed_id
  = f.submit 'Follow', class: 'btn btn-large btn-primary'

app/views/users/_follow_form.html.haml
.follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by(followed_id: @user.id), method: :delete) do |f|
  = f.submit 'Unfollow', class: 'btn btn-large btn-primary'

app/views/users/_user.html.haml
%li
  = gravatar_for user, size:52
  = link_to user.name, user
  - if current_user.admin? && current_user != user
    |
    = link_to 'delete', user_path(user), :method => 'delete', data: { confirm: "You sure?" }

app/views/users/edit.html.haml
- provide(:title, 'Edit user')
%h1 Update your profile

.row
  .span6.offset3
    = form_for @user do |f|
      = render 'fields', f: f
      = f.submit 'Save changes', class: "btn btn-large btn-primary"

    = gravatar_for(@user)
    = link_to 'Change', 'http://gravatar.com/emails', target: '_blank'

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users
  
= will_paginate
/ Rails is smart enough to detect the class type of an object and automatically look for
/ a partial with the same name, e.g. render user will look for a partial called _user, and
/ a collection of users (e.g. @users) will automatically be iterated and rendered
%ul.users
  = render @users
= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
.row
  .span6.offset3
    =form_for @user, url: signup_path do |f|
      = render 'fields', f: f
      = f.submit 'Create my account', class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)

.row
  %aside.span4
    %section
      %h1
        = gravatar_for(@user)
        = "#{@user.name}"

  .span8
    = render 'follow_form' if signed_in? && !current_user?(@user)
    - if @user.microposts.any?
      %h3 Microposts (#{@user.microposts.count})
      %ol.microposts
        = render @microposts
      = will_paginate @microposts

app/views/users/show_follow.html.haml
- provide(:title, @title)
.row
  %aside.span4
    %section
      = gravatar_for @user
      %h1 #{@user.name}
      %span
        = link_to 'view my profile', @user
      %span
        %b Microposts:
        #{@user.microposts.count}
    %section
      = render 'shared/follow_stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .span8
    %h3 #{@title}
    - if @users.any?
      %ul.users
        = render @users
      = will_paginate @users